### ISSUE TITLE
TODO: Allow the host machine to be Debian/Ubuntu/Centos8/Fedora - The server itself needs to be rhel/centos/fedora?

### ISSUE THREAD

**Issue by toastbrotch** [ccamacho/kubeinit#4]
hi

as far as i understand the kubeinit setup is kvm-based and i'm aware that the whole okd-nodes need to be coreos/centos/fedora/rhel. but it should be possible to use kubeinit also on another other OS based Server (with minor changes), right?

i have a debian/kvm server and want to test okd there. i dont think i need to change much besides "kubeinit_provision_hypervisor_dependencies" (as some names possibly differ) and the OS-check?

thanx.ivo

**Comment by ccamacho** [comment]
@toastbrotch indeed I assumed the host is a centos8 machine, then all the workers must be coreos (okd 4.5 is only supported in coreos) the only one you might change in the cluster is the services guest besides the underlying host OS. I'll keep this open to test this in Debian with it's corresponding changes as it won't work out of the box. If you test it before I, please feel free to share your changes! Thanks for the feedback!

**Comment by toastbrotch** [comment]
@ccamacho ok. thanx for answering. yes, its really just about the underlaying host OS i want to test with debian (kvm/proxmox)...

**Comment by gnunn1** [comment]
Fedora 32 would be nice as well

**Comment by ccamacho** [comment]
@gnunn1 @toastbrotch This should work now on CentOS/Fedora Debian/Ubuntu hosts after a few minor changes.
