### ISSUE TITLE
Conflicts with existing KVM and DNS

### ISSUE THREAD

**Issue by beaulieumichel** [ccamacho/kubeinit#5]
I had a first try and found out that it conflict with my pre-existing  virbr1. 
As well, I already had named.service and the playbook is trying to change it.
Finally, I am running with Fedora 32, again another change to the playbook.
__
Ease of use seems to be there only when starting with a fresh install of the host.
I put this aside until I have more time. 
Not a simple 30 minutes in my case.

**Comment by ccamacho** [comment]
Hi, I already changed the default name of the bridge used for the guests @ https://github.com/ccamacho/kubeinit/blob/master/kubeinit/playbooks/okd.yml#L127

It should not conflict with an existing bridge, the named service is configured in the services VM so it should not conflict.
